output: a4.o decrement.o find.o findMaxIndex.o findMinIndex.o firstInFirstOut.o futureTable.o int_to_string.o leastRecentlyUsed.o optimal.o readFile.o writeFile.o
	g++ a4.o decrement.o find.o findMaxIndex.o findMinIndex.o firstInFirstOut.o futureTable.o int_to_string.o leastRecentlyUsed.o optimal.o readFile.o writeFile.o -o output

main.o: a4.cpp
	g++ -c a4.cpp

decrement.o: decrement.cpp decrement.h
	g++ -c decrement.cpp

find.o: find.cpp find.h
	g++ -c find.cpp

findMaxIndex.o: findMaxIndex.cpp findMaxIndex.h
	g++ -c findMaxIndex.cpp

findMinIndex.o: findMinIndex.cpp findMinIndex.h
	g++ -c findMinIndex.cpp

firstInFirstOut.o: firstInFirstOut.cpp firstInFirstOut.h
	g++ -c firstInFirstOut.cpp

futureTable.o: futureTable.cpp futureTable.h
	g++ -c futureTable.cpp

int_to_string.o: int_to_string.cpp int_to_string.h
	g++ -c int_to_string.cpp

leastRecentlyUsed.o: leastRecentlyUsed.cpp leastRecentlyUsed.h
	g++ -c leastRecentlyUsed.cpp

optimal.o: optimal.cpp optimal.h
	g++ -c optimal.cpp

readFile.o: readFile.cpp readFile.h
	g++ -c readFile.cpp

writeFile.o: writeFile.cpp writeFile.h
	g++ -c writeFile.cpp